[package]
name = "ale-systems-core"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
object = { version = "=0.39.1", default-features = false, features = ["read_core", "elf", "pe", "macho", "std"] }
iced-x86 = { version = "=1.21.0", default-features = false, features = ["std", "decoder", "intel", "instr_info"] }
gimli = { version = "=0.32.3", default-features = false, features = ["read", "std"] }
